imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        driver: pdo_mysql
        host: localhost
        port: ~
        dbname: noveo_test_db
        user: root
        password: root
        charset: UTF8

liip_functional_test: ~
