imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@NoveoTestBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
#    serializer: { enable_annotations: true }
    templating:
        engines: ['php'] #we dont need twig - we dont have any html forms
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

fos_rest:
    body_listener:
        enabled: true
        default_format: json
    param_fetcher_listener:
        enabled: true
    routing_loader:
        default_format: json
        include_format: false
    body_converter:
        enabled: true
        validate: true
    serializer:
        serialize_null: true
    view:
        view_response_listener:
            enabled: true
            force: true
        force_redirects:
            json: true
    exception:
        enabled: true
        codes:
            'JMS\Serializer\Exception\InvalidArgumentException': 400
            'Doctrine\ORM\EntityNotFoundException': 404
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': 409
            'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException': 405


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: NoveoTestBundle\Entity\User
    group:
        group_class: NoveoTestBundle\Entity\Group
    use_username_form_type: false
    service:
        mailer: fos_user.mailer.noop
    registration:
        confirmation:
            enabled: false
    from_email:
        address: "foo@bar.buz"
        sender_name: "Nobody"

jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-d H:i:s"
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"

sensio_framework_extra:
    request:
        converters: true